In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [4]:
c = np.linspace(1,10,5)
c

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
d = np.zeros((2,2))
d

array([[0., 0.],
       [0., 0.]])

In [7]:
e = np.ones((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
f = np.full((5,),7)
f

array([7, 7, 7, 7, 7])

In [10]:
g = np.full((5,2,),9)
g

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [19]:

h = np.fromstring('5 10 15 20 25', dtype=np.int32, sep=' ')
h

array([ 5, 10, 15, 20, 25])

In [20]:
np.around([0.17,1.64,1.5,1.49])

array([0., 2., 2., 1.])

In [22]:
np.around([0.17,1.64,1.5,1.49],decimals=1)

array([0.2, 1.6, 1.5, 1.5])

In [23]:
a

array([1, 2, 3, 4, 5])

In [24]:
a.sum()

15

In [26]:
a= np.array([[1,2,3],[4,5,6]])
a.sum(axis=0)

array([5, 7, 9])

In [27]:
a.sum()

21

In [28]:
a.sum(axis=1)

array([ 6, 15])

In [29]:
price = np.array([300,400,450,500,600])
price.min()

300

In [30]:
price.max()

600

In [31]:
price.mean()

450.0

In [32]:
price.var()

10000.0

In [33]:
price.std()

100.0

In [34]:
price.argmin()

0

In [35]:
price.argmax()

4

In [8]:
txt_data = np.genfromtxt('data.txt',skip_header=1,delimiter=',',dtype=np.int32)
txt_data

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]])

In [7]:
txt_data = np.loadtxt('data.txt',skiprows=1,delimiter=',',dtype=np.int32)
txt_data

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]])

In [9]:
multiple_of_five = txt_data*5
multiple_of_five

array([[  5,  10,  15,  20,  25],
       [  5,  15,  25,  35,  45],
       [ 10,  20,  30,  40,  50],
       [ 10,  15,  25,  35,  55],
       [ 10,  20,  40,  80, 160]])

In [11]:
np.savetxt('new_data.txt',multiple_of_five,delimiter=',',fmt='%d',header='v1;v2;v3;v4;v5',comments=' ')